name: User
targets:
  User:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [User]
    info:
      path: ./Info.plist
      version: 1.3.11
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
