//
// AnAPIToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AnAPIToken: Codable {

    /** The resource of the token.  The token applies to the specified resource and any resources below this so the resource &#x60;/&#x60; applies to the root resource and any resource below the root resource. In the same manner &#x60;/collections&#x60; will apply to all collectins while &#x60;/collections/{id}&#x60; will apply to that particular collection. */
    public var resource: String?
    /** Write flag for token.  If this is set to &#x60;true&#x60; the token can be used for write operations in the API such as POST, DELETE and PATCH. */
    public var write: Bool?
    /** Tags for the token. */
    public var tags: [String: String]?
    /** The last time the token was used. Time in ms since epoch. */
    public var lastUse: String?
    public var uses: String?

    public init(resource: String? = nil, write: Bool? = nil, tags: [String: String]? = nil, lastUse: String? = nil, uses: String? = nil) {
        self.resource = resource
        self.write = write
        self.tags = tags
        self.lastUse = lastUse
        self.uses = uses
    }

}
