//
// ATeam.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ATeam: Codable {

    public var isPrivate: Bool?
    public var tags: [String: String]?
    public var members: [Member]?

    public init(isPrivate: Bool? = nil, tags: [String: String]? = nil, members: [Member]? = nil) {
        self.isPrivate = isPrivate
        self.tags = tags
        self.members = members
    }

}
