//
// DeleteTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeleteTokenResponse: Codable {

    public var token: Token?

    public init(token: Token? = nil) {
        self.token = token
    }

}
