//
// DeleteInviteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeleteInviteResponse: Codable {

    public var invite: Invite?

    public init(invite: Invite? = nil) {
        self.invite = invite
    }

}
