//
// InviteList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** List of active invites. Onece an invite has been redeemed it will be removed automatically. An administrator of the team can delete unused invites. */
public struct InviteList: Codable {

    public var invites: [Invite]?

    public init(invites: [Invite]? = nil) {
        self.invites = invites
    }

}
