//
// InviteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InviteRequest: Codable {

    public var teamId: String?
    /** The invite code. */
    public var code: String?

    public init(teamId: String? = nil, code: String? = nil) {
        self.teamId = teamId
        self.code = code
    }

}
