//
// Invite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Invite. Invites are used to share access to teams. You must be an administrator to generate invites for a team. */
public struct Invite: Codable {

    public var code: String?
    /** Time stamp when the invite was generated. */
    public var createdAt: String?

    public init(code: String? = nil, createdAt: String? = nil) {
        self.code = code
        self.createdAt = createdAt
    }

}
