//
// MemberOfATeam.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MemberOfATeam: Codable {

    public var role: String?
    public var user: UserProfile?

    public init(role: String? = nil, user: UserProfile? = nil) {
        self.role = role
        self.user = user
    }

}
