//
// MemberList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MemberList: Codable {

    public var members: [Member]?

    public init(members: [Member]? = nil) {
        self.members = members
    }

}
