//
// ProtobufAny.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProtobufAny: Codable {

    public var typeUrl: String?
    public var value: Data?

    public init(typeUrl: String? = nil, value: Data? = nil) {
        self.typeUrl = typeUrl
        self.value = value
    }

}
