//
// RequestInviteDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RequestInviteDetails: Codable {

    /** The invite code. */
    public var code: String?

    public init(code: String? = nil) {
        self.code = code
    }

}
