//
// RpcStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RpcStatus: Codable {

    public var code: Int?
    public var message: String?
    public var details: [ProtobufAny]?

    public init(code: Int? = nil, message: String? = nil, details: [ProtobufAny]? = nil) {
        self.code = code
        self.message = message
        self.details = details
    }

}
