//
// TeamList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TeamList: Codable {

    public var teams: [Team]?

    public init(teams: [Team]? = nil) {
        self.teams = teams
    }

}
