//
// Team.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Team: Codable {

    public var teamId: String?
    public var isPrivate: Bool?
    public var tags: [String: String]?
    public var members: [Member]?

    public init(teamId: String? = nil, isPrivate: Bool? = nil, tags: [String: String]? = nil, members: [Member]? = nil) {
        self.teamId = teamId
        self.isPrivate = isPrivate
        self.tags = tags
        self.members = members
    }

}
