//
// TokenList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TokenList: Codable {

    public var tokens: [Token]?

    public init(tokens: [Token]? = nil) {
        self.tokens = tokens
    }

}
