//
// UserProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Your user profile. You can change the contents of the user profile via the log in service you are using. */
public struct UserProfile: Codable {

    public var userId: String?
    public var email: String?
    public var avatarUrl: String?
    public var name: String?
    public var profileUrl: String?
    public var githubLogin: String?
    public var provider: String?
    public var logoutUrl: String?

    public init(userId: String? = nil, email: String? = nil, avatarUrl: String? = nil, name: String? = nil, profileUrl: String? = nil, githubLogin: String? = nil, provider: String? = nil, logoutUrl: String? = nil) {
        self.userId = userId
        self.email = email
        self.avatarUrl = avatarUrl
        self.name = name
        self.profileUrl = profileUrl
        self.githubLogin = githubLogin
        self.provider = provider
        self.logoutUrl = logoutUrl
    }

}
